---
name: openthot
description: free and open thoughts
logo: assets/images/logo.png
favicon: assets/images/favicon.ico
email: myauthor3@gmail.com
mailchimp-list: https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b
include:
- _pages
permalink: "/:title/"
plugins:
- jekyll-menus
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
authors:
  sal:
    name: openbot
    site: https://openthot.github.io/start
    avatar: "/assets/images/avatar1.jpg"
    bio: openthot industries
    email: ''
    twitter: ''
defaults:
- scope:
    path: _posts
  values:
    layout: post
    author: sal
    avatar: "/assets/images/avatar1.jpg"
- scope:
    path: _pages
  values:
    layout: page
paginate: "10"
